### PR TITLE
Make module map selection target-aware.

### PR DESCRIPTION
**Pull request by smcallis**
Before the cc_toolchain module_map depended only on the execution platform so something like this:

`bazel build //some:target`

followed by:

`bazel build --platforms=@llvm//platforms:linux_arm64_gnu.2.28 //third_party:smoke`

Would fail because it would try to use the x86 module map for ARM.

To fix it, we make platform_module_map depend on the target as well.

CC toolchains are now always named:
   {exec_os}_{exec_cpu}_to_{target_os}_{target_cpu}_cc_toolchain

To prevent existing client breakage, we alias the old names to the new "cross-compiler" toolchain:
   {exec_os}_{exec_cpu}_to_{exec_os}_{exec_cpu}_cc_toolchain

Then we can define a module map and linux target headers target for each combination of target cpu and libc configuration. This is only for linux targets, other targets remain the same.

### CODE REVIEW

**Comment by dzbarsky** [comment]
@smcallis can you share a repro so we can take a look what's going on? Your description of the issue is pretty surprising, it almost sounds like you're running without sandboxing or something? Would love to verify exactly what's going on though so we can also add regression tests!

**Comment by smcallis** [comment]
Sure I ran into this specifically compiling Abseil as a dependency. It seems to grab the kernel headers a little more aggressively than most. Running `bazel build :main` followed by `bazel build --config=arm64 :main` in the same root with this should fail. 

I tested it on my linux desktop and OSX laptop and both failed.  Here's the failure from OSX which I think is a little more clear. You can see it's looking for some system headers that aren't available due to the stale modmap:

```ERROR: /<redacted>/851345b0eb5e05f6b3e897b9c2092dc8/external/abseil-cpp+/absl/base/BUILD.bazel:126:11: Compiling absl/base/internal/spinlock_wait.cc failed: (Exit 1): clang++ failed: error executing CppCompile command (from target @@abseil-cpp+//absl/base:spinlock_wait) external/llvm++_repo_rules+llvm-toolchain-minimal-22.1.0-darwin-arm64/bin/clang++ -target aarch64-linux-gnu -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' ... (remaining 95 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from bazel-out/darwin_arm64-fastbuild/bin/external/abseil-cpp+/absl/base/spinlock_wait.cppmap:13:
In file included from bazel-out/darwin_arm64-fastbuild/bin/external/abseil-cpp+/absl/base/../../../../../../../bazel-out/darwin_arm64-fastbuild/bin/external/abseil-cpp+/absl/base/base_internal.cppmap:11:
bazel-out/darwin_arm64-fastbuild/bin/external/abseil-cpp+/absl/base/../../../../../../../bazel-out/darwin_arm64-fastbuild/bin/external/abseil-cpp+/absl/base/../../../../../../../bazel-out/darwin_arm64-fastbuild/bin/external/llvm++_repo_rules+llvm-toolchain-minimal-22.1.0-darwin-arm64/module_map.modulemap:16:5: error: umbrella directory '../../../../../external/llvm++kernel_headers+linux_kernel_headers_x86.5.9.16/include' not found [-Werror,-Wincomplete-umbrella]
   16 |     umbrella "../../../../../external/llvm++kernel_headers+linux_kernel_headers_x86.5.9.16/include"
      |     ^
bazel-out/darwin_arm64-fastbuild/bin/external/abseil-cpp+/absl/base/../../../../../../../bazel-out/darwin_arm64-fastbuild/bin/external/abseil-cpp+/absl/base/../../../../../../../bazel-out/darwin_arm64-fastbuild/bin/external/llvm++_repo_rules+llvm-toolchain-minimal-22.1.0-darwin-arm64/module_map.modulemap:24:5: error: umbrella directory '../../../../../external/llvm++glibc+glibc_headers_x86_64-linux-gnu.2.32/include' not found [-Werror,-Wincomplete-umbrella]
   24 |     umbrella "../../../../../external/llvm++glibc+glibc_headers_x86_64-linux-gnu.2.32/include"
      |     ^
In file included from external/abseil-cpp+/absl/base/internal/spinlock_wait.cc:22:
external/abseil-cpp+/absl/base/internal/spinlock_wait.h:21:10: error: module abseil-cpp+//absl/base:spinlock_wait does not depend on a module exporting 'stdint.h'
   21 | #include <stdint.h>
      |          ^
In file included from external/abseil-cpp+/absl/base/internal/spinlock_wait.cc:27:
external/abseil-cpp+/absl/base/internal/spinlock_linux.inc:17:10: error: module abseil-cpp+//absl/base:spinlock_wait does not depend on a module exporting 'linux/futex.h'
   17 | #include <linux/futex.h>
      |          ^
external/abseil-cpp+/absl/base/internal/spinlock_linux.inc:18:10: error: module abseil-cpp+//absl/base:spinlock_wait does not depend on a module exporting 'sys/syscall.h'
   18 | #include <sys/syscall.h>
      |          ^
external/abseil-cpp+/absl/base/internal/spinlock_linux.inc:19:10: error: module abseil-cpp+//absl/base:spinlock_wait does not depend on a module exporting 'unistd.h'
   19 | #include <unistd.h>
      |          ^
6 errors generated.
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.167s, Critical Path: 0.55s
INFO: 453 processes: 73 action cache hit, 139 internal, 314 darwin-sandbox.
ERROR: Build did NOT complete successfully
```

[repro.tar.gz](https://github.com/user-attachments/files/26677490/repro.tar.gz)

**Comment by keith** [comment]
i bisected this to being fixed by https://github.com/bazelbuild/bazel/commit/98c77ea4d79520ec2a4150d38007f7c8b38c3958 in the 8.x branch, first released with 8.5.0

**Comment by smcallis** [comment]
OK I'll try that this evening then, I might have to force bazelisk to pick up the later bazel.

**Comment by smcallis** [comment]
Confirmed, this works on Bazel >= 8.5.0, that's my bad for not ensuring I was up to date. Thanks for the help!

**Comment by keith** [comment]
https://github.com/hermeticbuild/hermetic-llvm/pull/453

**Comment by keith** [comment]
not your fault! thanks for the report, I think we'd probably want to merge this if we cared too much about that version, but hopefully anyone on 8.x should be safe enough to update
